api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_py"
location.oci = "docker.io/getobelisk/benchmark_fibo_fiboa_py:2025-12-08@sha256:28145f8c43ebf6a996bed6de41d18b1d53401c1bacd22a2fa44883cc98a894e3"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_py"
location.oci = "docker.io/getobelisk/benchmark_fibo_fibow_py:2025-12-08@sha256:853fedbc78fb3fcf23ed6e041fdf130f7cd1017e0c141628bf68bd302fc1501e"
exec.lock_expiry.seconds = 2
