api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_py"
location.oci = "docker.io/getobelisk/benchmark_fibo_fiboa_py:2025-12-18@sha256:e60b2cb31cc805dcc487e2fecbf72556e5beb33212a3e986f580807d7771b081"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_py"
location.oci = "docker.io/getobelisk/benchmark_fibo_fibow_py:2025-12-18@sha256:43055307c04f3bcdd5cf19e62a239367799de9c2631b5b7fbe6faf503e9bf29a"
exec.lock_expiry.seconds = 2
