api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_rs"
location.oci = "docker.io/getobelisk/benchmark_fibo_fiboa_rs:2025-12-08@sha256:bbeb3e6354faa5e5bca3aec4b8477ded055fff7d3707f6fc9a493d1c15601de3"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_rs"
location.oci = "docker.io/getobelisk/benchmark_fibo_fibow_rs:2025-12-08@sha256:438b356a3d49d760adb67a1be04936d102a3e272fbbf600b963406a4d10b68d2"
exec.lock_expiry.seconds = 2
