api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_go"
location.oci = "docker.io/getobelisk/benchmark_fibo_fiboa_go:2025-12-18@sha256:e848ac73b23934d173ef9d8a9874fb78b6fc2b65468885ad3af0d8578c0d09bf"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_go"
location.oci = "docker.io/getobelisk/benchmark_fibo_fibow_go:2025-12-18@sha256:cf1665459bceb943f927d629f34ac104cbfcd30e974e61101b0e45063d639e38"
exec.lock_expiry.seconds = 2
stub_wasi = true # TinyGo limitation
