api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_js"
location.oci = "docker.io/getobelisk/benchmark_fibo_fiboa_js:2025-12-08@sha256:61589514f209c2ae1de1007208cfcdbe63a73f65f4c5f9fd78b2b796325ecb8f"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_js"
location.oci = "docker.io/getobelisk/benchmark_fibo_fibow_js:2025-12-08@sha256:10d30f8e74925eaff1cea6bfd82a84e63b96cd1b720356c04b92c57c35075c08"
exec.lock_expiry.seconds = 2
